FROM golang:1.19

# create a working directory inside the image
WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod ./
RUN go mod download && go mod verify

# copy directory files i.e all files ending with .go

COPY . .

# tells Docker that the container listens on specified network ports at runtime
EXPOSE 8081

CMD ["top"]