  
version: '3'
services:
  curso-golang:
    build: .
    ports:
      - "8081:8081"
    container_name: container-curso-golang
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - go-net
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # Accept remote connections
      MYSQL_ROOT_HOST: '%'   
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    container_name: container-curso-golang-mysql
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - go-net
networks:
  go-net:
    driver: bridge
    
# Names our volume
volumes:
  my-db:

    